spring:
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/personal/shopping/dal/persistence/*Mapper.xml"
  type-aliases-package: com.personal.shopping.dal.entitys
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    TAlarmInformationMapper: debug