dubbo:
  application:
    name: lxwshopping-user
    owner: LXW
  registry:
    address: zookeeper://120.79.28.199:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://120.79.28.199:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.personal.user

captchaFlag : true