spring:
  redisson:
    address: 120.79.28.199:6379
    timeout: 3000
    database: 0
    password:
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.79.28.199:3306/shopping_mysql?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
dubbo:
  application:
    name: user-service
    owner: LXW
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://120.79.28.199:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://120.79.28.199:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.personal.user.services
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/personal/user/datamodel/persistence/*.xml
  type-aliases-package: com.personal.user.datamodel.entitys

logging:
  level:
    TAlarmInformationMapper: debug