dubbo:
  application:
    name: lxwshopping-shopping
    owner: violetdream
  registry:
    address: zookeeper://localhost:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://localhost:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.personal.shopping
